package pl.antonic.androidcv.methods

enum class Methods {
    CONTOURS_FINDING,
    HISTOGRAM_EQUALIZATION,
    BILATERAL_FILTER,
    GAUSSIAN_BLUR,
    EROSION,
    DILATION,
    OPENING,
    CLOSING,
    BLACK_HAT,
    GRADIENT,
    TOP_HAT,
    LINE_EXTRACT,
    BASIC_THRESHOLD,
    SOBEL_DERIVATIVES,
    LAPLACE_OPERATOR,
    HISTOGRAM_CALCULATION,
    CONVEX_HULL,
    CANNY_EDGE_DETECTOR
}